### ISSUE TITLE
Evaluación de motores para implementación de base de datos

### ISSUE THREAD

**Issue by daniherreraa** [ISCOUTB/AG-Nebula#2]

**Comment by saray-b** [comment]
Para el análisis de motores para implementación de base de datos en nuestro proyecto se planteó la comparativa entre PostgreSQL y MySQL y se revela que PostgreSQL es la opción más adecuada debido a sus características avanzadas en manejo de datos y análisis. 
Teniendo las siguientes características:

**Escalabilidad y volumen de datos**
•	Para archivos pequeños o medianos (menos de varios gigabytes), PostgreSQL o MySQL pueden ser más que suficientes y también más fáciles de implementar.

**Tipo de datos y flexibilidad del esquema**
•	Para datos estructurados y que siguen un esquema claro (filas y columnas consistentes), una base de datos relacional como PostgreSQL o MySQL es más adecuada.

**Facilidad de uso y administración**
•	PostgreSQL y MySQL son conocidos por ser relativamente fáciles de implementar y administrar, con una gran comunidad y abundantes recursos de soporte.

**Costo**
•	PostgreSQL y MySQL son gratuitos si se utilizan en infraestructura local, o bien más baratos en servicios de nube si se configuran en servidores autogestionados.

Por otra parte, existen ciertas ventajas clave por parte de PostgreSQL:

**Concurrencia y consistencia transaccional:**
•	PostgreSQL implementa MVCC (Control Multiversión de Concurrencia) de manera más efectiva, lo que significa que es mejor para manejar transacciones complejas y concurrentes. Esto es crucial si múltiples usuarios están interactuando con la base de datos al mismo tiempo para subir archivos, ejecutar análisis o entrenar modelos.
•	MySQL tiene un sistema de bloqueo de tablas que puede volverse un cuello de botella en casos de alta concurrencia.

**Consultas complejas y rendimiento analítico:**
•	PostgreSQL se caracteriza por tener capacidad para manejar consultas complejas y analíticas de manera eficiente, lo que es ideal para un sistema que implica análisis de datos y modelos predictivo. Sus características avanzadas incluyen soporte completo para subconsultas, funciones de ventana, y manejo de CTEs (Common Table Expressions).

PostgreSQL ofrece una mejor gestión de grandes volúmenes de datos y mayor flexibilidad para trabajar con tipos de datos complejos, lo que es clave en un entorno donde se espera trabajar con modelos predictivos. 
En conclusión, PostgreSQL es la opción más robusta y flexible para un sistema que debe manejar, procesar y analizar datos de manera eficiente, permitiendo futuros desarrollos y expansiones sin comprometer el rendimiento.

**Comment by jairoserrano** [comment]
@saray-b adelante.
