### ISSUE TITLE
Revisión de infraestructura (Docker)

### ISSUE THREAD

**Issue by daniherreraa** [ISCOUTB/AG-Nebula#4]

**Comment by diegoMartinez12** [comment]
Infraestructura Docker
1. Componentes principales del sistema
a. Backend 
Esta parte del sistema será responsable de cargar los archivos CSV, procesarlos, entrenar los modelos de regresión o clasificación y devolver los resultados
b. Frontend:
La interfaz gráfica de usuario que permite cargar los archivos, seleccionar variables, visualizar los resultados y exportar los informes. 
c. Base de Datos:
Este componente almacenará información sobre los usuarios, las configuraciones de los modelos, resultados previos, y otros metadatos importantes.
d. Servicio de Procesamiento:
Se encargará de ejecutar el procesamiento de los datos, el entrenamiento de los modelos y la generación de las métricas de rendimiento.

Planificación de la Infraestructura
Definiremos el Dockerfile para cada servicio (backend, frontend, procesamiento, base de datos). crearemos un Dockerfile que prepare el entorno de Python para la API backend.
Escribiremos el archivo docker-compose.yml para orquestar los servicios, definiendo cómo deben interactuar entre sí.

**Comment by diegoMartinez12** [comment]
Infraestructura Docker

Componentes principales del sistema
a. Backend
Esta parte del sistema será responsable de cargar los archivos CSV, procesarlos, entrenar los modelos de regresión o clasificación y devolver los resultados
b. Frontend:
La interfaz gráfica de usuario que permite cargar los archivos, seleccionar variables, visualizar los resultados y exportar los informes.
c. Base de Datos:
Este componente almacenará información sobre los usuarios, las configuraciones de los modelos, resultados previos, y otros metadatos importantes.
d. Servicio de Procesamiento:
Se encargará de ejecutar el procesamiento de los datos, el entrenamiento de los modelos y la generación de las métricas de rendimiento.
Planificación de la Infraestructura
Definiremos el Dockerfile para cada servicio (backend, frontend, procesamiento, base de datos). crearemos un Dockerfile que prepare el entorno de Python para la API backend.
Escribiremos el archivo docker-compose.yml para orquestar los servicios, definiendo cómo deben interactuar entre sí.

**Comment by jairoserrano** [comment]
adelante.
