### ISSUE TITLE
Diseño de interfaz con Mockup interactivo en Figma

### ISSUE THREAD

**Issue by daniherreraa** [ISCOUTB/AG-Nebula#5]

**Comment by daniherreraa** [comment]
Prototipado NebulaApp con Figma

https://www.figma.com/proto/gs9mV4ypDVkPhAjowsro1l/Nebula-Project?page-id=8%3A6&node-id=24-6&node-type=frame&viewport=1701%2C190%2C0.77&t=lc5s1rgl2npLdFQ2-1&scaling=scale-down&content-scaling=fixed

**Comment by jairoserrano** [comment]
adelante
